#!/bin/zsh

assert() {
       if [[ "$2" != "$3" ]]; then
       	   echo "Failure: $1\n\tExpected: $3\n\tReceived: $2"
	   ERR=1
       fi
}

local ASV='./asv'
local SOH=$'\001'
local STX=$'\002'
local FS=$'\034'
local GS=$'\035'
local RS=$'\0'
local FS=$'\036'
local US=$'\037'

TMP=$(mktemp)
trap "rm $TMP" EXIT

THEAD="${SOH}a${FS}b${RS}"
TBODY="${STX}c${FS}d${RS}e${FS}f${RS}"

assert 'add header' "$($ASV header <(echo $TBODY) a b)" "$(echo $THEAD$TBODY)"
assert 'replace header' "$($ASV header <(echo $THEAD$TBODY) x y)" "$(echo "${SOH}x${FS}y$RS$TBODY")"

echo 'a b\nc d' > "$TMP"
assert 'tokenize' "$($ASV tokenize $TMP)" "$(echo "${SOH}token${RS}${STX}a${RS}b${RS}c${RS}d${RS}")"
assert 'tokenize filenames' "$($ASV tokenize -f $TMP)" "$(echo "${SOH}filename${FS}token${RS}${STX}$TMP${FS}a${RS}$TMP${FS}b${RS}$TMP${FS}c${RS}$TMP${FS}d${RS}")"

assert 'tsv2asv' "$($ASV tsv2asv <(echo "a\tb\nc\td\ne\tf"))" "$(echo "${STX}a${FS}b${RS}c${FS}d${RS}e${FS}f${RS}")"

[[ -z "$ERR" ]] && echo "All Tests Pass"
exit "$ERR"


